site_name: PSRAW - PowerShell Reddit API Wrapper Module
site_author: Mark Kraus
repo_url: https://github.com/markekraus/PSRAW/
theme: readthedocs
copyright: "PSRAW is licensed under the <a href='https://github.com/markekraus/PSRAW/raw/master/LICENSE'>MIT license"
pages:
  - Home: index.md
  - PSRAW Project:
    - Contributing to PSRAW: Project/Contributing.md
    - Project News: Project/News.md
  - Change Log: ChangeLog.md
  - Module Help:
    - PSRAW: Module/PSRAW.md
    - about_RedditApiResponse: Module/about_RedditApiResponse.md
    - about_RedditApplication: Module/about_RedditApplication.md
    - about_RedditApplicationType: Module/about_RedditApplicationType.md
    - about_RedditComment: Module/about_RedditComment.md
    - about_RedditDate: Module/about_RedditDate.md
    - about_RedditModReport: Module/about_RedditModReport.md
    - about_RedditOAuthDuration: Module/about_RedditOAuthDuration.md
    - about_RedditOAuthGrantType: Module/about_RedditOAuthGrantType.md
    - about_RedditOAuthResponseType: Module/about_RedditOAuthResponseType.md
    - about_RedditOAuthScope: Module/about_RedditOAuthScope.md
    - about_RedditOAuthToken: Module/about_RedditOAuthToken.md
    - about_RedditThing: Module/about_RedditThing.md
    - about_RedditThingPrefix: Module/about_RedditThingPrefix.md
    - about_RedditUserReport: Module/about_RedditUserReport.md
    - Export-RedditApplication: Module/Export-RedditApplication.md
    - Export-RedditOAuthToken: Module/Export-RedditOAuthToken.md
    - Get-RedditOAuthScope: Module/Get-RedditOAuthScope.md
    - Import-RedditApplication: Module/Import-RedditApplication.md
    - Import-RedditOAuthToken: Module/Import-RedditOAuthToken.md
    - Invoke-RedditRequest: Module/Invoke-RedditRequest.md
    - New-RedditApplication: Module/New-RedditApplication.md
    - Request-RedditOAuthToken: Module/Request-RedditOAuthToken.md
    - Update-RedditOAuthToken: Module/Update-RedditOAuthToken.md
  - Private Functions:
    - Get-AuthorizationHeader: PrivateFunctions/Get-AuthorizationHeader.md
    - Request-RedditOAuthTokenClient: PrivateFunctions/Request-RedditOAuthTokenClient.md
    - Request-RedditOAuthTokeninstalled: PrivateFunctions/Request-RedditOAuthTokeninstalled.md
    - Request-RedditOAuthTokenPassword: PrivateFunctions/Request-RedditOAuthTokenPassword.md
    - Wait-RedditApiRateLimit: PrivateFunctions/Wait-RedditApiRateLimit.md
  - Examples:
    - Quickstart Example: Examples/Quickstart.md

